#!/usr/bin/env python3
#title      : 
#description: 
#author     : ${gh-user}
#date       : ${date}
#version    : ${date}a
#notes      : 
#copyright  : Copyright (C) ${year} ${gh-user}  (${gh-email})
#license    : Permission to copy and modify is granted under the MIT license
