#!/usr/bin/env python3
#title      : 
#description: 
#author     : ${gh-user}
#date       : ${date}
#version    : ${date}a
#notes      : 
#copyright  : Copyright (C) ${year} ${gh-user}  (${gh-email})
#license    : Permission to copy and modify is granted under the MIT license

__VERSION__ = ${data}a
__TITLE__ = ""

def main():
    return None

if __name__ == "__main__":
    print(f"{__TITLE__} - v{__VERSION__}")
    main()
