#!/usr/bin/env bash
#title           :
#description     :
#author          :${gh-user}
#date            :${date}
#version         :v${date}a
#notes           :
#copyright       :Copyright (C) ${year} ${gh-user} (${gh-email})
#license         :Permission to copy and modify is granted under the MIT license

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh arg-one arg-two

This is an awesome bash script to make your life better.

'
    exit
fi

cd "$(dirname "$0")"

main() {
    echo do awesome stuff;
}

main "$@"
